RecipesRealm/Controllers/CategoryController.cs
using RecipesRealm.ViewModels;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System;

namespace RecipesRealm.Controllers {
    public class CategoryController : BaseController {

        public CategoryController(IRecipeRecommendationEngine recipeRecommendationEngine) : base(recipeRecommendationEngine) {
        }

        public ActionResult Details(long id) {
            try {
                var categ = recipeRecommendationEngine.GetCategoryById(id);

                var model = AutoMapperConfig.Mapper.Map<CategoryViewModel>(categ);
                var recipes = recipeRecommendationEngine.GetRecipes(id);
                ICollection<RecipeViewModel> recipesVMs = new List<RecipeViewModel>();

                foreach (var r in recipes) {
                    var rVM = AutoMapperConfig.Mapper.Map<RecipeViewModel>(r);

                    recipesVMs.Add(rVM);
                }

                model.Recipes = recipesVMs;

                return View(model);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on getting Category Details");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }
    }
}

RecipesRealm/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using ModelsLibrary;
using RecipesRealm.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using System.IO;
using System.Web.Hosting;
using System.Web;

namespace RecipesRealm.Controllers {
    public class RecipeController : BaseController {

        public RecipeController(IRecipeRecommendationEngine recipeRecommendationEngine) : base(recipeRecommendationEngine) {
        }

        public ActionResult Index() {
            try {
                IEnumerable<RecipeViewModel> recipeViewModels = new List<RecipeViewModel>();
                IEnumerable<Recipe> recipes = recipeRecommendationEngine.GetRecipesList();

                if (recipes is null) {
                    logger.Warn("Recipes List Empty");
                }

                foreach (Recipe r in recipes)
                    recipeViewModels = recipeViewModels.Append(AutoMapperConfig.Mapper.Map<RecipeViewModel>(r));

                return View(recipeViewModels);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on Getting Recipes");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

        #region Create

        public ActionResult Create() {
            try {
                RecipeViewModel recipeViewModel = new RecipeViewModel();

                //all categories
                ICollection<CategoryViewModel> recipeAllCategories = new List<CategoryViewModel>();
                var allCategs = recipeRecommendationEngine.GetCategoriesList();

                foreach (var categ in allCategs)
                    recipeAllCategories.Add(AutoMapperConfig.Mapper.Map<CategoryViewModel>(categ));

                recipeViewModel.AllCategories = recipeAllCategories;

                //all tags
                ICollection<TagViewModel> recipeAllTags = new List<TagViewModel>();
                var allTags = recipeRecommendationEngine.GetTagsList();

                foreach (var tag in allTags)
                    recipeAllTags.Add(AutoMapperConfig.Mapper.Map<TagViewModel>(tag));

                recipeViewModel.AllTags = recipeAllTags;

                //all nutrition elements
                ICollection<NutritionElementViewModel> recipeAllNutritionElements = new List<NutritionElementViewModel>();
                var allNElems = recipeRecommendationEngine.GetNutritionElementsList();

                foreach (var nElem in allNElems)
                    recipeAllNutritionElements.Add(AutoMapperConfig.Mapper.Map<NutritionElementViewModel>(nElem));

                recipeViewModel.AllNutritionElements = recipeAllNutritionElements;

                //all ingredients
                ICollection<IngredientViewModel> recipeAllIngredients = new List<IngredientViewModel>();
                var allIngreds = recipeRecommendationEngine.GetIngredientsList();

                foreach (var ingred in allIngreds)
                    recipeAllIngredients.Add(AutoMapperConfig.Mapper.Map<IngredientViewModel>(ingred));

                recipeViewModel.AllIngredients = recipeAllIngredients;

                return View(recipeViewModel);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on Getting Recipe Model for Creation");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

        [Microsoft.AspNetCore.Mvc.Produces("application/json")]
        public string UploadPhoto(HttpPostedFileBase file) {
            try {
                if (file != null) {
                    var path = Path.Combine(HostingEnvironment.ApplicationPhysicalPath, "Content/Images", file.FileName);
                    file.SaveAs(path);

                    return "/Content/Images/" + file.FileName;
                }
                return "";
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on Uploading Recipe file");
                return ex.ToString();
            }
        }

        [HttpPost]
        public ActionResult Create(RecipeViewModel model) {
            try {
                if (ModelState.IsValid) {
                    Recipe recipe = AutoMapperConfig.Mapper.Map<Recipe>(model);

                    recipe.Is_Active = true;
                    recipe.Creation_Date = DateTime.Now;

                    ICollection<RecipeTag> recipeTags = new List<RecipeTag>();

                    foreach (var tagId in model.RecipeTagsIds) {
                        var recipeTag = new RecipeTag {
                            Recipe_ID = 0,
                            Tag_ID = tagId
                        };

                        recipeTags.Add(recipeTag);
                    }

                    recipe.RecipeTags = recipeTags;

                    ICollection<RecipeCategory> recipeCategories = new List<RecipeCategory>();

                    foreach (var catId in model.RecipeCategoriesIds) {
                        var recipeCateg = new RecipeCategory {
                            Recipe_ID = 0,
                            Category_ID = catId
                        };

                        recipeCategories.Add(recipeCateg);
                    }

                    recipe.RecipeCategories = recipeCategories;

                    var id = recipeRecommendationEngine.AddRecipe(recipe);

                    return RedirectToAction("Details", new { id });
                }

                ViewBag.Warning = "Could not Create Recipe";
                return View();
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on Creating Recipe");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

        #endregion Create

        #region Details

        public ActionResult Details(long id) {
            try {
                var recipe = recipeRecommendationEngine.GetRecipe(id);
                RecipeViewModel recipeViewModel = new RecipeViewModel();

                if (recipe == null) {
                    ViewBag.Warning = "The recipe could not be found";
                    return View(recipeViewModel);
                }

                recipeViewModel = AutoMapperConfig.Mapper.Map<RecipeViewModel>(recipe);

                recipeViewModel.Author_Name = recipeRecommendationEngine.GetUserName(recipe.Author_User_ID);
                recipeViewModel.AverageRating = recipeRecommendationEngine.GetAverageRatingForRecipe(id);


                return View(recipeViewModel);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on getting Recipe Details");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }

        }

        #endregion Details


        #region Edit

        public ActionResult Edit(long id) {
            try {
                var recipe = recipeRecommendationEngine.GetRecipe(id);
                RecipeViewModel recipeViewModel = new RecipeViewModel();

                if (recipe == null) {
                    ViewBag.Warning = "The recipe could not be found";
                    return View(recipeViewModel);
                }

                recipeViewModel = AutoMapperConfig.Mapper.Map<RecipeViewModel>(recipe);

                recipeViewModel.Author_Name = recipeRecommendationEngine.GetUserName(recipe.Author_User_ID);
                recipeViewModel.AverageRating = recipeRecommendationEngine.GetAverageRatingForRecipe(id);
                recipeViewModel.RecipeCategoriesIds = recipeRecommendationEngine.GetCategoriesIdsForRecipe(id);
                recipeViewModel.RecipeTagsIds = recipeRecommendationEngine.GetTagsIdsForRecipe(id);

                //all categories
                ICollection<CategoryViewModel> recipeAllCategories = new List<CategoryViewModel>();
                var allCategs = recipeRecommendationEngine.GetCategoriesList();
                foreach (var categ in allCategs)
                    recipeAllCategories.Add(AutoMapperConfig.Mapper.Map<CategoryViewModel>(categ));
                recipeViewModel.AllCategories = recipeAllCategories;

                //all tags
                ICollection<TagViewModel> recipeAllTags = new List<TagViewModel>();
                var allTags = recipeRecommendationEngine.GetTagsList();
                foreach (var tag in allTags)
                    recipeAllTags.Add(AutoMapperConfig.Mapper.Map<TagViewModel>(tag));
                recipeViewModel.AllTags = recipeAllTags;

                //all nutrition elements
                ICollection<NutritionElementViewModel> recipeAllNutritionElements = new List<NutritionElementViewModel>();
                var allNElems = recipeRecommendationEngine.GetNutritionElementsList();
                foreach (var nElem in allNElems)
                    recipeAllNutritionElements.Add(AutoMapperConfig.Mapper.Map<NutritionElementViewModel>(nElem));
                recipeViewModel.AllNutritionElements = recipeAllNutritionElements;

                //all ingredients
                ICollection<IngredientViewModel> recipeAllIngredients = new List<IngredientViewModel>();
                var allIngreds = recipeRecommendationEngine.GetIngredientsList();
                foreach (var ingred in allIngreds)
                    recipeAllIngredients.Add(AutoMapperConfig.Mapper.Map<IngredientViewModel>(ingred));
                recipeViewModel.AllIngredients = recipeAllIngredients;

                return View(recipeViewModel);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on getting Recipe for Edit");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

        [HttpPost]

RecipesRealm/Controllers/RecommendationController.cs
using Microsoft.AspNetCore.Http;
using ModelsLibrary;
using RecipesRealm.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using System;

namespace RecipesRealm.Controllers {
    public class RecommendationController : BaseController {

        public RecommendationController(IRecipeRecommendationEngine recipeRecommendationEngine) : base(recipeRecommendationEngine) {
        }

        public ActionResult Index(long? id) {
            try {
                IEnumerable<RecipeViewModel> recipeViewModels = new List<RecipeViewModel>();

                if (id.HasValue) {

                    IEnumerable<Recipe> recipes = recipeRecommendationEngine.GenerateRecommendations(id.Value);

                    foreach (Recipe r in recipes)
                        recipeViewModels = recipeViewModels.Append(AutoMapperConfig.Mapper.Map<RecipeViewModel>(r));

                }
                else {
                    IEnumerable<Recipe> recipes = recipeRecommendationEngine.GenerateRecommendationsNoUser(null);

                    foreach (Recipe r in recipes)
                        recipeViewModels = recipeViewModels.Append(AutoMapperConfig.Mapper.Map<RecipeViewModel>(r));
                }

                return View(recipeViewModels);
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on Getting Recommendations");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }
    }
}

RecipesRealm/Controllers/UserController.cs
using RecipesRealm.ViewModels;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ModelsLibrary;
using Microsoft.AspNetCore.Http;
using System;
using System.Linq;

namespace RecipesRealm.Controllers {
    public class UserController : BaseController {

        public UserController(IRecipeRecommendationEngine recipeRecommendationEngine) : base(recipeRecommendationEngine) {
        }

        [Produces("application/json")]
        public string Login(string modelString) {
            try {
                UserViewModel userVM = JsonConvert.DeserializeObject<UserViewModel>(modelString);
                User user = AutoMapperConfig.Mapper.Map<User>(userVM);

                User loggedInUser = recipeRecommendationEngine.CheckUserForLogin(user);

                if (loggedInUser != null) {
                    return JsonConvert.SerializeObject(new { userName = loggedInUser.User_Name, userId = loggedInUser.User_ID });
                }

                return JsonConvert.SerializeObject(new { userId = -1 });
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on User Login");
                return ex.ToString();
            }
        }

        [Produces("application/json")]
        public string SignUp(string modelString) {
            try {
                UserViewModel userVM = JsonConvert.DeserializeObject<UserViewModel>(modelString);
                User user = AutoMapperConfig.Mapper.Map<User>(userVM);

                bool emailExists = recipeRecommendationEngine.CheckUserEmailExists(user.Email_Address);
                if (emailExists) {
                    return JsonConvert.SerializeObject(new { userId = -1, EmailExists = true });
                }

                User loggedInUser = recipeRecommendationEngine.SignUpUser(user);

                if (loggedInUser != null) {
                    return JsonConvert.SerializeObject(new { userName = loggedInUser.User_Name, userId = loggedInUser.User_ID });
                }

                return JsonConvert.SerializeObject(new { userId = -1 });
            }
            catch (Exception ex) {
                logger.Error(ex, "Error on User Signup");
                return ex.ToString();
            }
        }

        public System.Web.Mvc.ActionResult MyRecipes(long id) {
            try {
                IEnumerable<RecipeViewModel> recipeViewModels = new List<RecipeViewModel>();
                IEnumerable<Recipe> recipes = recipeRecommendationEngine.GetUserRecipes(id);

                if (recipes is null) {
                    logger.Warn("User Recipes List Empty");
                }

                foreach (Recipe r in recipes)
                    recipeViewModels = recipeViewModels.Append(AutoMapperConfig.Mapper.Map<RecipeViewModel>(r));

                return View(recipeViewModels);
            }

            catch (Exception ex) {
                logger.Error(ex, "Error on getting User Recipes");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

        public System.Web.Mvc.ActionResult SavedRecipes(long id) {
            try {
                IEnumerable<RecipeViewModel> recipeViewModels = new List<RecipeViewModel>();
                IEnumerable<Recipe> recipes = recipeRecommendationEngine.GetUserSavedRecipes(id);

                if (recipes is null) {
                    logger.Warn("User Saved Recipes List Empty");
                }

                foreach (Recipe r in recipes)
                    recipeViewModels = recipeViewModels.Append(AutoMapperConfig.Mapper.Map<RecipeViewModel>(r));

                return View(recipeViewModels);
            }

            catch (Exception ex) {
                logger.Error(ex, "Error on getting User Saved Recipes");
                return new HttpStatusCodeResult(StatusCodes.Status500InternalServerError, ex.ToString());
            }
        }

    }
}

RecipesRealm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <header id="main-header" class="main-header ">
        <div class="header-content stick ">
            <div id="my-header" class="my-header container-fluid">
                <div class="container">
                    <div class="navbar-header">
                        <a id="main-logo" class="logo" href="/">
                            <img src="~/Content/Assets/Logo.png" alt="logo" />
                        </a>
                    </div>
                    <nav id="site-nav" class="site-nav">
                        <div class="nav-1 ">
                            <ul>
                                <li>
                                    @Html.ActionLink("Recipes", "Index", "Recipe")
                                </li>
                                <li class="has-submenu">
                                    @Html.ActionLink("Discover", "Index", "Category")
                                    <ul id="dropdown" class="submenu submenu-category row">
                                        @foreach (var el in ViewBag.LayoutModel.Categories) {
                                            string catName = el.Category_Name;
                                            <li class="submenu-heading col-4">
                                                @Html.ActionLink(catName, "Details", "Category", new { id = el.Category_ID }, new { })
                                            </li>
                                        }
                                    </ul>
                                </li>
                                <li id="recommendationLink">
                                    @Html.ActionLink("Recommendations", "Index", "Recommendation")
                                </li>
                            </ul>
                        </div>
                        <div class="nav-2">
                            <ul>
                                <li class="site-search d-none">
                                    <span><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 27.6 27.6"><path d="M26.5 22.7l-4.4-4.4c1.2-1.8 1.9-4 1.9-6.3C24 5.5 18.8.3 12.3.3 5.8.3.6 5.6.6 12s5.2 11.7 11.7 11.7c2.3 0 4.5-.7 6.3-1.9l4.4 4.4c1 1 2.6 1 3.5 0 1-.9 1-2.5 0-3.5zm-14.2-2.3c-4.6 0-8.3-3.7-8.3-8.3s3.7-8.3 8.3-8.3c4.6 0 8.3 3.7 8.3 8.3 0 4.5-3.7 8.3-8.3 8.3z" /></svg></span>
                                    <div id="search" class="container-fluid">
                                        <div class="container">
                                            <div class="search-input">
                                                <div class="input-wrapper">
                                                    <i class="search-icon"></i>
                                                    <form id="site-search" method="get" action="/search/">
                                                        <input type="text" placeholder="Search for anything" class="typeahead input_text clear_search" name="s">
                                                        <input type="submit" value="Search">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="login-container invisible">
                                    <div class="login-links">
                                        <a onclick="$.fn.showSignUp();" href="#">Sign up</a>
                                        <i>/</i>
                                        <a onclick="$.fn.showLogin();" href="#">Log in</a>
                                    </div>
                                </li>
                                <li class="logged-in d-none has-submenu">
                                    <p></p>
                                    <ul id="dropdown" class="submenu submenu-user row">
                                        <li class="submenu-heading w-auto mx-4">
                                            @Html.ActionLink("Add Recipe", "Create", "Recipe")
                                        </li>
                                        <li class="submenu-heading w-auto mx-4 myRecipesLink">
                                            @Html.ActionLink("My Recipes", "MyRecipes", "User")
                                        </li>
                                        <li class="submenu-heading w-auto mx-4 savedRecipesLink">
                                            @Html.ActionLink("Saved Recipes", "SavedRecipes", "User")
                                        </li>
                                        <li class="submenu-heading w-auto mx-4">
                                            <a onclick="$.fn.logOut();" href="#">Log out</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="modal fade" id="loginModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title loginTitle">Login</h5>
                    <h5 class="modal-title signUpTitle d-none">Sign Up</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="login-block">
                        <form id="loginForm">
                            <label for="login_Email">Email Address</label>
                            <input type="text" placeholder="E-mail address" id="login_Email" class="form-control mb-3" />
                            <label for="login_Password">Password</label>
                            <input type="password" placeholder="Password" id="login_Password" class="form-control mb-2" />
                            <div class="text-danger invisible mb-3" id="login-error">* Email or Password is incorrect</div>
                            <input type="submit" value="Login" class="btn form-control mb-3" id="loginBtn" />
                        </form>
                        <p>Not a user? <a href="#" onclick="$.fn.showSignUp();">Sign up</a> instead</p>
                    </div>
                    <div class="signup-block d-none">
                        <form id="signUpForm">
                            <label for="signUp_Username">User Name</label>
                            <input type="text" placeholder="User Name" id="signUp_Username" class="form-control mb-3" />
                            <label for="signUp_Email">Email Address</label>
                            <input type="text" placeholder="E-mail address" id="signUp_Email" class="form-control mb-3" />
                            <label for="signUp_Password">Password</label>
                            <input type="password" placeholder="Password" id="signUp_Password" class="form-control mb-2" />
                            <div class="text-danger invisible mb-3" id="signup-error">* Signing up error</div>
                            <input type="submit" value="Sign Up" class="btn form-control mb-3" id="signUpBtn" />
                        </form>
                        <p>Already a user? <a href="#" onclick="$.fn.showLogin();">Login</a> instead</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <link rel="stylesheet" href="~/Content/filter_multi_select.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo&family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <script src="~/Scripts/filter-multi-select-bundle.min.js"></script>
    @RenderSection("scripts", required: false)
</body>

<script>

    $.fn.showLogin = function () {
        $('.signup-block').addClass('d-none');
        $('.signUpTitle').addClass('d-none');

        $('.login-block').removeClass('d-none');
        $('.loginTitle').removeClass('d-none');

        $('#loginModal').modal('show');
    }

    $.fn.showSignUp = function () {
        $('.login-block').addClass('d-none');
        $('.loginTitle').addClass('d-none');

        $('.signup-block').removeClass('d-none');
        $('.signUpTitle').removeClass('d-none');

        $('#loginModal').modal('show');
    }

    $.fn.logOut = function () {
        localStorage.removeItem("loggedInUserName");
        localStorage.removeItem("loggedInUserId");

        window.location = '/';
    }

    $(document).ready(function () {

        if (localStorage.getItem("loggedInUserName") != undefined) {
            $('.login-container').addClass('d-none');
            $('.logged-in p').html("Hello, " + localStorage.getItem("loggedInUserName"));
            $('.logged-in').removeClass('d-none');
        }
        else {
            $('.login-container').removeClass('invisible');
        }

        if (localStorage.getItem("loggedInUserId") != undefined) {
            var strs = $('#recommendationLink a').attr('href').split('/Index');
            if (strs.length == 1 || strs[1].length < 2) {
                $('#recommendationLink a').attr('href', $('#recommendationLink a').attr('href') + '/Index/' + localStorage.getItem("loggedInUserId"));
            }
            strs = $('.myRecipesLink a').attr('href').split('/MyRecipes');
            if (strs[1].length < 2) {
                $('.myRecipesLink a').attr('href', $('.myRecipesLink a').attr('href') + '/' + localStorage.getItem("loggedInUserId"));
            }

            strs = $('.savedRecipesLink a').attr('href').split('/SavedRecipes');
            if (strs[1].length < 2) {
                $('.savedRecipesLink a').attr('href', $('.savedRecipesLink a').attr('href') + '/' + localStorage.getItem("loggedInUserId"));
            }
        }

        $('#loginForm').submit(function (e) {
            e.preventDefault();

            var formData = new FormData();

            var model = {
                Email_Address: $('#login_Email').val(),
                Password: $('#login_Password').val()
            };

            var modelStr = JSON.stringify(model);

            formData.append("modelString", modelStr);

            $.ajax({
                type: "POST",
                url: '/User/Login',
                data: formData,
                async: false,
                cache: false,
                contentType: false,
                processData: false,
                timeout: 60000,
                success: function (user) {
                    var u = JSON.parse(user);

                    if (u.userId != -1) {
                        localStorage.setItem("loggedInUserName", u.userName);
                        localStorage.setItem("loggedInUserId", u.userId);

                        window.location = '/';
                    }
                    else {
                        $('#login-error').removeClass('invisible');
                    }
                },
                error: function (error) {
                    console.log(error);

                    $('#login-error').removeClass('invisible');
                }

            });

            return false;
        })

        $('#signUpForm').submit(function (e) {
            e.preventDefault();

            var formData = new FormData();

            var model = {
                User_Name: $('#signUp_Username').val(),
                Email_Address: $('#signUp_Email').val(),
                Password: $('#signUp_Password').val()
            };

            var modelStr = JSON.stringify(model);

            formData.append("modelString", modelStr);

            $.ajax({
                type: "POST",
                url: '/User/SignUp',
                data: formData,
                async: false,
                cache: false,
                contentType: false,
                processData: false,
                timeout: 60000,
                success: function (user) {
                    var u = JSON.parse(user);

                    if (u.userId != -1) {
                        localStorage.setItem("loggedInUserName", u.userName);
                        localStorage.setItem("loggedInUserId", u.userId);

                        window.location = '/';
                    }
                    else {
                        if (u.EmailExists != undefined) {
                            $('#signup-error').html("An user with this E-mail Address already exists!");
                        }
                        $('#signup-error').removeClass('invisible');
                    }
                },
                error: function (error) {
                    console.log(error);

                    $('#signup-error').removeClass('invisible');
                }

            });

            return false;
        })
    })

</script>

</html>